### ISSUE TITLE
Play page login fails - Stage 3

### ISSUE THREAD

**Issue by PhillCli** [fedorovvl/tsoclient_docker#2]
[This line check fails](https://github.com/fedorovvl/tsoclient_docker/blob/main/tsoclient/entrypoint#L163), and data response at stage3 returns HTML that cannot be parsed into TSO URI.

I'm unfamiliar with how authorization is set up to debug it further.

PS. Do you accept pull requests? I wanted to create a GithubActions workflow to rebuild the docker image and push it to the docker-hub automatically. It can be triggered manually and automatically update client.swf (Downloading one from `https://sirris.tsomaps.com/client.swf`). Simplifying release schedule.

**Comment by fedorovvl** [comment]
after last maintenance linux version not working.. coz there is a new mail type enum 96 that swf doesn't know
so even if i fix login stage you get assert error after bootloader
in windows version i made custom library.swf for that, in linux.. don't know how to repeat

feel free to make PR

**Comment by PhillCli** [comment]
I see, that's a shame.

Unfortunately, I'm not skilled with the SWF build chain either, nor the history of how exactly the source for client.swf was obtained to have it fixed/be able to load `library.swf` to handle that.
As I understand, TSOClient loads `client.swf`, so modification would be required, but without source code, isn't it impossible?

Your Windows client is written in .NET, right? That's a pain to build on Linux as well, not even thinking about porting GUI libraries calls.

**Comment by fedorovvl** [comment]
no source code for client.swf =)
i've modify client.swf opcodes with ffdec tool.. but it is very difficult to change complex sections of code with it
i maybe try again a bit later

**Comment by fedorovvl** [comment]
pls check latest tag/code

**Comment by PhillCli** [comment]
> pls check latest tag/code

Logged in and loaded correctly! Thanks!

though I had to add `chown` so that client.swf update can write into `/tso/share/client.swf`:

```git
--- a/Dockerfile
+++ b/Dockerfile
@@ -10,7 +10,8 @@ ADD tsoclient /tso
 
 RUN dpkg -i /tso/python3-six_1.16.0-2_all.deb && \
     dpkg -i /tso/python3-dateutil_2.8.1-6_all.deb && \
-    cp /tso/globalRuntime.conf /etc/opt/Adobe\ AIR/
+    cp /tso/globalRuntime.conf /etc/opt/Adobe\ AIR/ && \
+    chown -R user:user /tso/share
 
 USER user
 RUN mkdir -p /home/user/.appdata/Adobe/AIR && \
``` 

Great work, do you have any "patronite" links or another donation page?

**Comment by fedorovvl** [comment]
> Great work, do you have any "patronite" links or another donation page?

most donation platforms not useful in Russia since recently.. you know.. sanctions =)
chown added

**Comment by PhillCli** [comment]
@fedorovvl crypto wallet?

**Comment by fedorovvl** [comment]
> @fedorovvl crypto wallet?

@PhillCli  btc: bc1quulssa0eaqw8umd86sxxlnphtntm0y6vdreplm
